# Render.com deployment configuration for FastAPI backend
version: 2
services:
  - type: web
    name: vaultmind-backend
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: AUTH0_DOMAIN
        sync: false
      - key: AUTH0_AUDIENCE  
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: TOKEN_VAULT_ENDPOINT
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0